# Generated by Django 6.0 on 2026-06-06 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_contract_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.contract'),
        ),
    ]
